# SPDX-FileCopyrightText: 2021 Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
#
# SPDX-License-Identifier: BSD-2-Clause

name: Linting

on:
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run:  pip install -r requirements-dev.txt

    - name: Run Linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}

        black:      true
        black_dir:  src

        flake8:     true
        flake8_dir: src

        mypy:       true
        mypy_dir:   src
        mypy_args:  --strict

        pylint:     true
        pylint_dir: src
